/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bingwang' at '10/19/17 5:09 PM' with Gradle 2.14
 *
 * @author bingwang, @date 10/19/17 5:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
